server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 테이블 자동생성 아님 (이미 DB에 존재)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    path: /swagger-ui.html


ocr:
  base-url: http://localhost:8000
